# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_arrow_cpp6.0.2numpy1.20python3.7.____cpython:
        CONFIG: linux_64_arrow_cpp6.0.2numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp6.0.2numpy1.20pyt_h13b1cf8e00
      linux_64_arrow_cpp6.0.2numpy1.20python3.8.____cpython:
        CONFIG: linux_64_arrow_cpp6.0.2numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp6.0.2numpy1.20pyt_h4d85402ec6
      linux_64_arrow_cpp6.0.2numpy1.20python3.9.____cpython:
        CONFIG: linux_64_arrow_cpp6.0.2numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp6.0.2numpy1.20pyt_h6493ede080
      linux_64_arrow_cpp6.0.2numpy1.21python3.10.____cpython:
        CONFIG: linux_64_arrow_cpp6.0.2numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp6.0.2numpy1.21pyt_h60b43114e2
      linux_64_arrow_cpp7.0.1numpy1.20python3.7.____cpython:
        CONFIG: linux_64_arrow_cpp7.0.1numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp7.0.1numpy1.20pyt_h93d401aeae
      linux_64_arrow_cpp7.0.1numpy1.20python3.8.____cpython:
        CONFIG: linux_64_arrow_cpp7.0.1numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp7.0.1numpy1.20pyt_h2ae20f9752
      linux_64_arrow_cpp7.0.1numpy1.20python3.9.____cpython:
        CONFIG: linux_64_arrow_cpp7.0.1numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp7.0.1numpy1.20pyt_h3974406853
      linux_64_arrow_cpp7.0.1numpy1.21python3.10.____cpython:
        CONFIG: linux_64_arrow_cpp7.0.1numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp7.0.1numpy1.21pyt_h0513cf0149
      linux_64_arrow_cpp8.0.1numpy1.20python3.7.____cpython:
        CONFIG: linux_64_arrow_cpp8.0.1numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp8.0.1numpy1.20pyt_h8a44138a8b
      linux_64_arrow_cpp8.0.1numpy1.20python3.8.____cpython:
        CONFIG: linux_64_arrow_cpp8.0.1numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp8.0.1numpy1.20pyt_h92d4e493e8
      linux_64_arrow_cpp8.0.1numpy1.20python3.9.____cpython:
        CONFIG: linux_64_arrow_cpp8.0.1numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp8.0.1numpy1.20pyt_he3d244db7a
      linux_64_arrow_cpp8.0.1numpy1.21python3.10.____cpython:
        CONFIG: linux_64_arrow_cpp8.0.1numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp8.0.1numpy1.21pyt_h51cf8fd49a
      linux_64_arrow_cpp9.0.0numpy1.20python3.7.____cpython:
        CONFIG: linux_64_arrow_cpp9.0.0numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp9.0.0numpy1.20pyt_hbceb73f364
      linux_64_arrow_cpp9.0.0numpy1.20python3.8.____cpython:
        CONFIG: linux_64_arrow_cpp9.0.0numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp9.0.0numpy1.20pyt_h1e1b2d3cd2
      linux_64_arrow_cpp9.0.0numpy1.20python3.9.____cpython:
        CONFIG: linux_64_arrow_cpp9.0.0numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp9.0.0numpy1.20pyt_h6651fc3728
      linux_64_arrow_cpp9.0.0numpy1.21python3.10.____cpython:
        CONFIG: linux_64_arrow_cpp9.0.0numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_arrow_cpp9.0.0numpy1.21pyt_h76a67779bf
      linux_aarch64_arrow_cpp6.0.2numpy1.20python3.7.____cpython:
        CONFIG: linux_aarch64_arrow_cpp6.0.2numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp6.0.2numpy1._hde780eb253
      linux_aarch64_arrow_cpp6.0.2numpy1.20python3.8.____cpython:
        CONFIG: linux_aarch64_arrow_cpp6.0.2numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp6.0.2numpy1._hee8b8283ce
      linux_aarch64_arrow_cpp6.0.2numpy1.20python3.9.____cpython:
        CONFIG: linux_aarch64_arrow_cpp6.0.2numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp6.0.2numpy1._h6fb350c850
      linux_aarch64_arrow_cpp6.0.2numpy1.21python3.10.____cpython:
        CONFIG: linux_aarch64_arrow_cpp6.0.2numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp6.0.2numpy1._h500584f60c
      linux_aarch64_arrow_cpp7.0.1numpy1.20python3.7.____cpython:
        CONFIG: linux_aarch64_arrow_cpp7.0.1numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp7.0.1numpy1._h7001f5e0da
      linux_aarch64_arrow_cpp7.0.1numpy1.20python3.8.____cpython:
        CONFIG: linux_aarch64_arrow_cpp7.0.1numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp7.0.1numpy1._h948e8be766
      linux_aarch64_arrow_cpp7.0.1numpy1.20python3.9.____cpython:
        CONFIG: linux_aarch64_arrow_cpp7.0.1numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp7.0.1numpy1._hc6d695d41f
      linux_aarch64_arrow_cpp7.0.1numpy1.21python3.10.____cpython:
        CONFIG: linux_aarch64_arrow_cpp7.0.1numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp7.0.1numpy1._h59780a85a6
      linux_aarch64_arrow_cpp8.0.1numpy1.20python3.7.____cpython:
        CONFIG: linux_aarch64_arrow_cpp8.0.1numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp8.0.1numpy1._hb705d03603
      linux_aarch64_arrow_cpp8.0.1numpy1.20python3.8.____cpython:
        CONFIG: linux_aarch64_arrow_cpp8.0.1numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp8.0.1numpy1._h252d4a784c
      linux_aarch64_arrow_cpp8.0.1numpy1.20python3.9.____cpython:
        CONFIG: linux_aarch64_arrow_cpp8.0.1numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp8.0.1numpy1._h1dccad8893
      linux_aarch64_arrow_cpp8.0.1numpy1.21python3.10.____cpython:
        CONFIG: linux_aarch64_arrow_cpp8.0.1numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp8.0.1numpy1._ha2693cef8b
      linux_aarch64_arrow_cpp9.0.0numpy1.20python3.7.____cpython:
        CONFIG: linux_aarch64_arrow_cpp9.0.0numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp9.0.0numpy1._h0db49d2565
      linux_aarch64_arrow_cpp9.0.0numpy1.20python3.8.____cpython:
        CONFIG: linux_aarch64_arrow_cpp9.0.0numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp9.0.0numpy1._h4fdfce16fc
      linux_aarch64_arrow_cpp9.0.0numpy1.20python3.9.____cpython:
        CONFIG: linux_aarch64_arrow_cpp9.0.0numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp9.0.0numpy1._hee82d3d3cb
      linux_aarch64_arrow_cpp9.0.0numpy1.21python3.10.____cpython:
        CONFIG: linux_aarch64_arrow_cpp9.0.0numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_arrow_cpp9.0.0numpy1._hb1f0661f59
      linux_ppc64le_arrow_cpp6.0.2numpy1.20python3.7.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp6.0.2numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp6.0.2numpy1._h45feb0741b
      linux_ppc64le_arrow_cpp6.0.2numpy1.20python3.8.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp6.0.2numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp6.0.2numpy1._hfd514156c8
      linux_ppc64le_arrow_cpp6.0.2numpy1.20python3.9.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp6.0.2numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp6.0.2numpy1._h22130c82c6
      linux_ppc64le_arrow_cpp6.0.2numpy1.21python3.10.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp6.0.2numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp6.0.2numpy1._ha0a4fb5aef
      linux_ppc64le_arrow_cpp7.0.1numpy1.20python3.7.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp7.0.1numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp7.0.1numpy1._he7ce9afc45
      linux_ppc64le_arrow_cpp7.0.1numpy1.20python3.8.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp7.0.1numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp7.0.1numpy1._hd780a1a313
      linux_ppc64le_arrow_cpp7.0.1numpy1.20python3.9.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp7.0.1numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp7.0.1numpy1._hc342a513ad
      linux_ppc64le_arrow_cpp7.0.1numpy1.21python3.10.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp7.0.1numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp7.0.1numpy1._h5051f1b4dc
      linux_ppc64le_arrow_cpp8.0.1numpy1.20python3.7.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp8.0.1numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp8.0.1numpy1._hf5aa32589d
      linux_ppc64le_arrow_cpp8.0.1numpy1.20python3.8.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp8.0.1numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp8.0.1numpy1._h1237705d3d
      linux_ppc64le_arrow_cpp8.0.1numpy1.20python3.9.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp8.0.1numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp8.0.1numpy1._haae004e829
      linux_ppc64le_arrow_cpp8.0.1numpy1.21python3.10.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp8.0.1numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp8.0.1numpy1._hce9780fe30
      linux_ppc64le_arrow_cpp9.0.0numpy1.20python3.7.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp9.0.0numpy1.20python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp9.0.0numpy1._h5614ac0e94
      linux_ppc64le_arrow_cpp9.0.0numpy1.20python3.8.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp9.0.0numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp9.0.0numpy1._h27fb2063eb
      linux_ppc64le_arrow_cpp9.0.0numpy1.20python3.9.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp9.0.0numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp9.0.0numpy1._h1edde5d5eb
      linux_ppc64le_arrow_cpp9.0.0numpy1.21python3.10.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp9.0.0numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_arrow_cpp9.0.0numpy1._h8eb1d0debd
    maxParallel: 26
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        export CI=azure
        export CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        export CONDA_BLD_DIR=build_artifacts
        export ARTIFACT_STAGING_DIR="$(Build.ArtifactStagingDirectory)"
        # Archive everything in CONDA_BLD_DIR except environments
        export BLD_ARTIFACT_PREFIX=conda_artifacts
        if [[ "$AGENT_JOBSTATUS" == "Failed" ]]; then
          # Archive the CONDA_BLD_DIR environments only when the job fails
          export ENV_ARTIFACT_PREFIX=conda_envs
        fi
        ./.scripts/create_conda_build_artifacts.sh
    displayName: Prepare conda build artifacts
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Store conda build artifacts
    condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(BLD_ARTIFACT_PATH)
      artifactName: $(BLD_ARTIFACT_NAME)

  - task: PublishPipelineArtifact@1
    displayName: Store conda build environment artifacts
    condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(ENV_ARTIFACT_PATH)
      artifactName: $(ENV_ARTIFACT_NAME)